
name: input workflow

on:
  workflow_dispatch:
      inputs:
        inp1:
          description: 'Please Enter First String'
          required: false
          default: "___"
        inp2:
          description: 'Please Enter Second  String'
          default: "___"
          required: false

env:
  a: ${{github.event.inputs.inp1}}
  b: ${{github.event.inputs.inp2}}

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: |
          cd python
          python input.py $a $b

      - name: success message
        # run: echo program executed successfully on ubuntu-latest!!
        run: echo ${{github.event.inputs.inp1}}
             ${{github.event.inputs.inp2}}
